DROP DATABASE todolist;
CREATE DATABASE IF NOT EXISTS todolist;

USE todolist;
DROP TABLE IF EXISTS tarefa;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS usuario;

CREATE TABLE IF NOT EXISTS usuario(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categoria(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS tarefa(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(120) NULL,
    concluido BOOLEAN DEFAULT 0,
    prioridade ENUM("BAIXA", "MEDIA", "ALTA") DEFAULT "BAIXA",
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    categoria INT UNSIGNED,
    usuario INT UNSIGNED,
    FOREIGN KEY (categoria) REFERENCES categoria(id) ON DELETE SET NULL,
    FOREIGN KEY (usuario) REFERENCES usuario(id) ON DELETE CASCADE

);

INSERT INTO categoria(nome) VALUES
("PESSOAL"),
("TRABALHO"),
("EDUCAÇÃO"),
("CASA"),
("ALIMENTAÇÃO"),
("SAÚDE"),
("FINANÇAS"),
("LAZER"),
("OUTROS")